draw_config:
  append_colon_to_layer_header: false
  draw_key_sides: true
  dark_mode: auto

  svg_extra_style: |
    svg.keymap {
      font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
      font-size: 10px;
      font-weight: bold;
    }

    rect.held, rect.combo.held {
      fill: #ebdada;
    }

    .trans.tap, .ghost.tap {
      opacity: 0.5;
    }

    .shifted {
      translate: 15px 3px;
      opacity: 1.0;
    }
    text.hold {
      font-size: 10px;
      opacity: 1.0;
    }

    .toggle.shifted {
      translate: -12px 17px;
      opacity: 1.0;
    }
    .toggle.hold {
      translate: 12px -26px;
    }

    .text_with_symbol.tap {
      translate: -1px 1px;
    }
    .text_with_symbol.shifted {
      translate: 8px 13px;
      font-size: 8px;
      opacity: 1.0;
    }

    .combo.tap {
      font-size: 10px;
    }
    .combo.shifted {
      font-size: 8px;
      translate: 8px -0px;
    }
    .combo.hold {
        font-size: 10px;
        /* translate: 2px 0px; */
    }

    /* Variant for tap-dances */
    .tap_dance.tap {
      translate: -7px 0px;
      font-size: 12px;
    }
    .tap_dance.hold {
      translate: 7px -25px;
      font-size: 12px;
      opacity: 1.0;
    }
    .tap_dance.shifted {
      translate: 15px 3px;
      font-size: 16px;
      opacity: 1.0;
    }

    /* Variant for symbol next to symbol */
    .sym_by_sym.tap {
      translate: -5px 0px;
    }
    .sym_by_sym.shifted {
      translate: 8px 14.5px;
      font-size: 8px;
    }

    .sym_alt.tap {
      opacity: 1.0;
    }
    .sym_alt.shifted {
      translate: 15px 3px;
      opacity: 1.0;
    }
    .sym_alt.hold {
      opacity: 1.0;
    }
  
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 11
  use_local_cache: true
parse_config:
  preprocess: true
  skip_binding_parsing: false
  modifier_fn_map: null
  sticky_label: sticky
  toggle_label: $$material:toggle_on$$
  trans_legend:
    t: ▽
    type: trans
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
    PAGE_UP: 'PgUp'
    PAGE_DOWN: 'PgDn'
    HOME: 'Home'
    END: 'End'
    ESC: 'Esc'
    GLOBE: $$tabler:world$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE: $$mdi:backspace-outline$$
    DELETE: $$mdi:backspace-reverse-outline$$
    C_PP: $$mdi:play-pause$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$
    C_MUTE: $$mdi:volume-mute$$
    C_VOL_UP: $$mdi:volume-plus$$
    C_VOL_DN: $$mdi:volume-minus$$
    C_POWER: $$mdi:power$$
    C_SLEEP: $$mdi:power-sleep$$
    UP: $$mdi:arrow-up$$
    DOWN: $$mdi:arrow-down$$en
    LEFT: $$mdi:arrow-left$$
    RIGHT: $$mdi:arrow-right$$
    RETURN: $$mdi:keyboard-return$$
    ENTER: $$mdi:keyboard-return$$
    KP_NUMLOCK: Numlock
    TAB: $$mdi:keyboard-tab$$
    LEFT_GUI: $$mdi:apple-keyboard-command$$
    LGUI: $$mdi:apple-keyboard-command$$
    RIGHT_GUI: $$mdi:apple-keyboard-command$$
    RGUI: $$mdi:apple-keyboard-command$$
    LEFT_ALT: $$mdi:apple-keyboard-option$$
    LALT: $$mdi:apple-keyboard-option$$
    RIGHT_ALT: $$mdi:apple-keyboard-option$$
    RALT: $$mdi:apple-keyboard-option$$
    LEFT_SHIFT: $$material:shift$$
    LSHIFT: $$material:shift$$
    LSHFT: $$material:shift$$
    RIGHT_SHIFT: $$material:shift$$
    RSHIFT: $$material:shift$$
    RSHFT: $$material:shift$$
    RIGHT_CONTROL: $$material:keyboard_control_key$$
    RCTRL: $$material:keyboard_control_key$$
    LCTRL: $$material:keyboard_control_key$$
    LEFT_CONTROL: $$mdi:apple-keyboard-control$$
    LA(DOWN): $$material:move_down$$
    LA(UP): $$material:move_up$$
    LS(LA(I)): $$material:text_select_end$$
    PSCRN: $$material:screenshot_keyboard$$
    LC(Z): Undo
    LC(C): Copy
    LC(V): Paste
    LC(X): Cut
    LC(A): Sel_ALL
    LC(FSLH): Ctl+/
    LS(LA(DOWN)): 'Copy Down'
    LC(L): 'line select'
  raw_binding_map:
    "&bspc_del":
      tap: $$mdi:backspace-outline$$
      shifted: $$mdi:backspace-reverse-outline$$
      type: sym_alt
    "SYM_L 0":
      tap: $$mdi:backspace-outline$$
      shifted: $$mdi:backspace-reverse-outline$$
      hold: sym
      type: sym_alt
    "&sft_cap":
      tap: $$material:shift$$
      shifted: $$material:shift_lock$$
    "&qt_grave":
      tap: ''''
      hold: '"'
      shifted: '`'
      type: tap_dance
    "&sys_reset":
      tap: $$mdi:repeat-variant$$
      hold: Reset
    "&bootloader": 
      tap: $$mdi:reload$$
      hold: Boot
    "&bt BT_SEL 0":
      tap: $$material:bluetooth_connected$$
      shifted: 0
      type: sym_by_sym
    "&bt BT_SEL 1":
      tap: $$material:bluetooth_connected$$
      shifted: 1
      type: sym_by_sym
    "&bt BT_SEL 2":
      tap: $$material:bluetooth_connected$$
      shifted: 2
      type: sym_by_sym
    "&bt BT_SEL 3":
      tap: $$material:bluetooth_connected$$
      shifted: 3
      type: sym_by_sym
    "&bt BT_CLR":
      tap: $$material:bluetooth$$
      shifted: $$material:disabled_by_default$$
      type: sym_by_sym
    "&out OUT_BLE":
      tap: $$material:keyboard$$
      shifted: $$material:bluetooth$$
      type: sym_by_sym
    "&out OUT_USB":
      tap: $$material:keyboard$$
      shifted: $$material:cable$$
      type: sym_by_sym
    "&kp C_BRI_DN":
      tap: $$material:wb_sunny$$
      shifted: $$material:remove$$
      type: sym_by_sym
    "&kp C_BRI_UP":
      tap: $$material:wb_sunny$$
      shifted: $$material:add$$
      type: sym_by_sym
  zmk_combos:
    combo_bt: {align: top, o: 0.2}