file_format: "1"
id: nostrum
name: nostrum 
type: shield
url: https://github.com/bennytrouser/zmk-config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - nostrum_left
  - nostrum_right