file_format: "1"
id: benny
name: benny 
type: shield
url: https://github.com/bennytrouser/zmk-config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - benny_left
  - benny_right