on:
  workflow_dispatch:
  push:
    paths:
      - config/west.yml
      - config/*.keymap
      - config/*.conf
      - config/includes/*.dtsi
      - config/boards/shields/nostrumX/**  # Matches all files in this directory and subdirectories
      - config/boards/shields/nostrumchunky/**
      - build.yaml
      
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
